config/routes.rb
Educare::Application.routes.draw do

  root :to =>'posts#index'

  devise_for :users, :controllers => {:sessions => 'sessions', :registrations => 'registrations'}

  namespace :admin do
    resources :users
    resources :posts
    resources :categories
    resources :courses
    resources :teachers
  end

  resources :posts, :only => [:show, :index]
  resources :courses, :only => [:show, :index]
  resources :teachers, :only => [:show, :index]

  match '/gioi-thieu' => 'pages#about_us'

end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia
  include Mongoid::Slug
  include ScopedSearch::Model

  paginates_per 3

  field :title, type: String
  field :description, type: String
  field :body, type: String

  field :photo_uid, type: String
  image_accessor :photo

  attr_accessible :title, :description, :body, :user_id, :category_id, :photo, :photo_uid

  belongs_to :user
  belongs_to :category

  slug :title

  validates_presence_of :title, presence: true, :message => "This is a required field"
  validates_presence_of :body, presence: true, :message => "This is a required field"

  def thumb_photo_url
    photo ? photo.thumb('226x162').url : Settings.image.default
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  def index
    @search = Post.scoped_search(params[:search])
    if params[:commit] == 'Search' && !params[:from].blank? && !params[:to].blank?
      @posts = Post.where(:created_at.gte => Date.strptime(params[:from], '%d/%m/%Y'), :created_at.lte => Date.strptime(params[:to], '%d/%m/%Y'))
    elsif params[:commit] == 'Search' && !params[:from].blank? && params[:to].blank?
      @posts = Post.where(:created_at.gte => Date.strptime(params[:from], '%d/%m/%Y'))
      params[:to] = Date.today.strftime('%d/%m/%Y')
    elsif params[:commit] == 'Search' && params[:from].blank? && !params[:to].blank?
      @posts = Post.where(:created_at.lte => Date.strptime(params[:to], '%d/%m/%Y'))
    else
      @posts = @search.all
      if params['sort_by_title']
        session['post_sort'] = 'sort_by_title'
        @posts = @posts.sort { |o1, o2| o1.title <=> o2.title }
      else
        session['post_sort'] = nil
      end
    end

    if params['per_page']
      per_page = params['per_page']
      session['per_page'] = params['per_page']
    else
      per_page = 20
      session['per_page'] = nil
    end

    if session['user_sort']
      @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(per_page.to_i)
    else
      @posts = @posts.page(params[:page]).per(per_page.to_i)
    end
  end

  def resource
    @post ||= end_of_association_chain.find_by_slug(params[:id])
  end

  def create
    @post = Post.new(params[:post])
    @post.user = current_user
    @post.photo = params[:post][:photo]

    if @post.save
      redirect_to admin_post_path(@post)
    else
      render 'new'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.page(params[:page]).per(4)
  end

  def show
    @post = Post.find_by_slug(params[:id])
  end
end

app/views/admin/posts/_form.html.erb
  <div class="group">
    <%= f.label :category_id, t("activerecord.attributes.post.category_id", :default => "Category"), :class => :label %>
    <%= f.select :category_id, Category.all.map { |c| ["#{c.title}", c.id] }, include_blank: true %>
    <span class="description">Choise category name</span>
  </div>

  <div class="group">
    <%= f.label :title, t("activerecord.attributes.post.title", :default => "Title"), :class => :label %>
    <%= f.text_field :title, :class => 'text_field', style: "width: 650px !important; height: 20px;" %>
    <span class="description">Enter the title</span>
  </div>


  <div class="group">
    <%= f.label :photo, t("activerecord.attributes.post.photo_uid", :default => "Photo"), :class => :label %>
    <%= image_tag @post.photo.thumb('100x100').url if @post.photo_uid %>
    <%= f.file_field :photo, :class => 'file_field' %>
    <span class="description">Enter image</span>
  </div>

  <div class="group">
    <%= f.label :description, t("activerecord.attributes.post.description", :default => "Description"), :class => :label %>
    <%= f.text_area :description, :class => 'text_area', :style => "width: 100%; height: 100px;" %>
    <span class="description">Enter the description</span>
  </div>

  <div class="group">
    <%= f.label :body, t("activerecord.attributes.post.body", :default => "Body"), :class => :label %>
    <%= f.text_area :body, :class => 'ckeditor' %>
    <span class="description">Enter content</span>
  </div>

<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), admin_posts_path, :class => "text_button_padding link_button" %>
</div>

app/views/admin/posts/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/admin/posts/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_posts_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_post_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_post_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Post</h2>
    <div class="inner">
      <%= form_for @post, :url => admin_post_path(@post), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/posts/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_posts_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_post_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Posts</h2>
    <div class="inner">
      <table class="table">
        <tr>
          <th>
            <%= link_to 'Name', admin_posts_path(sort_by_title: true, per_page: "#{session['per_page'].nil? ? 20 : session['per_page']}" ) %>
          </th>
          <th>Category</th>
          <th>Created by</th>
          <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @posts.each do |post| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= link_to post.title, admin_post_path(post) %>
          </td>
          <td>
            <%= link_to post.category.title, admin_category_path(post.category) %>
          </td>
          <td><%= link_to post.user.full_name, admin_user_path(post.user) %></td>
          <td>
            <%= post.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_post_path(post) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_post_path(post) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_post_path(post), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
          <%= paginate @posts %>
        </div>

      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/posts/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_posts_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_post_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Post</h2>
    <div class="inner">
      <%= form_for :post, :url => admin_posts_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/posts/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_posts_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_post_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_post_path %></li>
    </ul>
  </div>
  <div class="content">
    <div class="inner">
        <p>
          <b><%= t("activerecord.attributes.admin_post.title", :default => t("activerecord.labels.title", :default => "Title")) %>:</b>
          <%= @post.title %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_post.description", :default => t("activerecord.labels.description", :default => "Description")) %>:</b>
          <%= @post.description %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_post.body", :default => t("activerecord.labels.body", :default => "Body")) %>:</b>
          <%= @post.body %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_post.user_id", :default => t("activerecord.labels.user_id", :default => "Created by")) %>:</b>
          <%= @post.user.full_name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_post.category_id", :default => t("activerecord.labels.category_id", :default => "Category")) %>:</b>
          <%= @post.category.nil? ? '' : @post.category.title %>
        </p>

      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_post_path(@post), :class => "button" %>
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_post_path(@post), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>