config/routes.rb
Educare::Application.routes.draw do

  root :to =>'posts#index'

  devise_for :users, :controllers => {:sessions => 'sessions', :registrations => 'registrations'}

  namespace :admin do
    resources :users
    resources :posts
    resources :categories
    resources :courses
    resources :teachers
  end

  resources :posts, :only => [:show, :index]
  resources :courses, :only => [:show, :index]
  resources :teachers, :only => [:show, :index]

  match '/gioi-thieu' => 'pages#about_us'

end

app/models/category.rb
class Category
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia
  include Mongoid::Slug
  include ScopedSearch::Model

  field :title, type: String
  field :description, type: String

  attr_accessible :title, :description, :posts

  slug :title
  has_many :posts
  # has_and_belongs_to_many :cate_ofs, class_name: "Category", inverse_of: :cates
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def index
    @search = Category.scoped_search(params[:search])
    if params[:commit] == 'Search' && !params[:from].blank? && !params[:to].blank?
      @categories = Category.where(:created_at.gte => Date.strptime(params[:from], '%d/%m/%Y'), :created_at.lte => Date.strptime(params[:to], '%d/%m/%Y'))
    elsif params[:commit] == 'Search' && !params[:from].blank? && params[:to].blank?
      @categories = Category.where(:created_at.gte => Date.strptime(params[:from], '%d/%m/%Y'))
      params[:to] = Date.today.strftime('%d/%m/%Y')
    elsif params[:commit] == 'Search' && params[:from].blank? && !params[:to].blank?
      @categories = Category.where(:created_at.lte => Date.strptime(params[:to], '%d/%m/%Y'))
    else
      @categories = @search.all
      if params['sort_by_title']
        session['user_sort'] = 'sort_by_title'
        @categories = @categories.sort { |o1, o2| o1.title <=> o2.title }
      else
        session['user_sort'] = nil
      end
    end

    if params['per_page']
      per_page = params['per_page']
      session['per_page'] = params['per_page']
    else
      per_page = 20
      session['per_page'] = nil
    end

    if session['user_sort']
      @categories = Kaminari.paginate_array(@categories).page(params[:page]).per(per_page.to_i)
    else
      @categories = @categories.page(params[:page]).per(per_page.to_i)
    end
  end

  def resource
    @category ||= end_of_association_chain.find(params[:id])
  end
end

app/views/admin/categories/_form.html.erb
  <div class="group">
    <%= f.label :title, t("activerecord.attributes.category.title", :default => "Title"), :class => :label %>
    <%= f.text_field :title, :class => 'text_field' %>
    <span class="description">Enter the title</span>
  </div>

  <div class="group">
    <%= f.label :description, t("activerecord.attributes.category.description", :default => "Description"), :class => :label %>
    <%= f.text_area :description, :class => 'text_area', :style => "width: 100%; height: 100px;" %>
    <span class="description">Enter the description</span>
  </div>

  <div class="group navform wat-cf">
    <button class="button" type="submit">
      <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
    </button>
    <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
  	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), admin_categories_path, :class => "text_button_padding link_button" %>
  </div>

app/views/admin/categories/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/admin/categories/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_categories_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_category_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_category_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Category</h2>
    <div class="inner">
      <%= form_for @category, :url => admin_category_path(@category), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/categories/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_categories_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_category_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Categories</h2>
    <div class="inner">
      <table class="table">
        <tr>
          <th>
            <%= link_to 'Title', admin_categories_path(sort_by_title: true, per_page: "#{session['per_page'].nil? ? 20 : session['per_page']}" ) %>
          </th>
          <th>Post number</th>
          <th>
            <%= t("web-app-theme.created_at", :default => "Created at")  %>
          </th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @categories.each do |category| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= link_to category.title, admin_category_path(category) %>
          </td>
          <td><%= category.posts.count %></td>
          <td>
            <%= category.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_category_path(category) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_category_path(category) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_category_path(category), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
          <%= paginate @categories %>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/categories/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_categories_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_category_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Category</h2>
    <div class="inner">
      <%= form_for :category, :url => admin_categories_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/categories/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_categories_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_category_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_category_path %></li>
    </ul>
  </div>
  <div class="content">
    <div class="inner">
        <p>
          <b><%= t("activerecord.attributes.admin_category.title", :default => t("activerecord.labels.title", :default => "Title")) %>:</b>
          <%= @category.title %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_category.description", :default => t("activerecord.labels.description", :default => "Description")) %>:</b>
          <%= @category.description %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_category_path(@category), :class => "button" %>
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_category_path(@category), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>
    </div>
  </div>
</div>

<div class="block">
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Posts of <%= @category.title %></h2>
    <div class="inner">
      <table class="table">
        <tr>
          <th class="first">ID</th>
          <th>Title</th>
          <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @category.posts.each do |post| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= post.id %>
          </td>
          <td>
            <%= link_to post.title, admin_post_path(post) %>
          </td>
          <td>
            <%= post.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_post_path(post) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_post_path(post) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_post_path(post), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>