config/routes.rb
Educare::Application.routes.draw do

  root :to =>'posts#index'

  devise_for :users, :controllers => {:sessions => 'sessions', :registrations => 'registrations'}

  namespace :admin do
    resources :users
    resources :posts
    resources :categories
    resources :courses
    resources :teachers
  end

  resources :posts, :only => [:show, :index]
  resources :courses, :only => [:show, :index]
  resources :teachers, :only => [:show, :index]

  match '/gioi-thieu' => 'pages#about_us'

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia
  include ScopedSearch::Model

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  field :full_name, :type => String
  field :address, :type => String
  field :phone_numer, :type => String
  field :role, :type => String, :default => Settings.user.roles.customer

  field :avatar_uid
  image_accessor :avatar

  validates :email, :presence => true, :uniqueness => true
  validates :role, :presence => true

  attr_accessible :full_name, :address, :phone_numer, :avatar_uid, :email, :courses, :posts

  scope :email_like, lambda { |email| where(:email => /#{email}/i) }
  scope :full_name_like, lambda { |full_name| where(:full_name => /#{full_name}/i) }

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
  #
  #
  has_many :posts
  has_and_belongs_to_many :courses, class_name: 'Course', inverse_of: :users

  def admin?
    self.role == Settings.user.roles.admin
  end

  def avatar_url
    avatar ? avatar.url : Settings.user.avatar
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @search = User.scoped_search(params[:search])
    if params[:commit] == 'Search' && !params[:from].blank? && !params[:to].blank?
      @users = User.where(:created_at.gte => Date.strptime(params[:from], '%d/%m/%Y'), :created_at.lte => Date.strptime(params[:to], '%d/%m/%Y'))
    elsif params[:commit] == 'Search' && !params[:from].blank? && params[:to].blank?
      @users = User.where(:created_at.gte => Date.strptime(params[:from], '%d/%m/%Y'))
      params[:to] = Date.today.strftime('%d/%m/%Y')
    elsif params[:commit] == 'Search' && params[:from].blank? && !params[:to].blank?
      @users = User.where(:created_at.lte => Date.strptime(params[:to], '%d/%m/%Y'))
    else
      @users = @search.all
      if params['sort_by_email']
        session['user_sort'] = 'sort_by_email'
        @users = @users.sort { |o1, o2| o1.email <=> o2.email }
      elsif params['sort_by_name']
        session['user_sort'] = 'sort_by_name'
        @users = @users.sort { |o1, o2| o1.last_name <=> o2.last_name }
      elsif params['sort_by_country']
        session['user_sort'] = 'sort_by_country'
        @users = @users.sort { |o1, o2| o1.country.to_s <=> o2.country.to_s }
      elsif params['sort_by_registration_date']
        session['user_sort'] = 'sort_by_registration_date'
        @users = @users.sort { |o1, o2| o1.created_at <=> o2.created_at }
      else
        session['user_sort'] = nil
      end
    end

    if params['per_page']
      per_page = params['per_page']
      session['per_page'] = params['per_page']
    else
      per_page = 20
      session['per_page'] = nil
    end

    if session['user_sort']
      @users = Kaminari.paginate_array(@users).page(params[:page]).per(per_page.to_i)
    else
      @users = @users.page(params[:page]).per(per_page.to_i)
    end
  end

  def resource
    @user ||= end_of_association_chain.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_without_password(params[:user])
      redirect_to admin_user_path(@user), notice: 'User was updated successfully'
    else
      reader 'edit'
    end
  end
end

app/views/admin/users/_form.html.erb
  <div class="group">
    <%= f.label :full_name, t("activerecord.attributes.user.full_name", :default => "Full name"), :class => :label %>
    <%= f.text_field :full_name, :class => 'text_field' %>
    <span class="description">Enter the full name</span>
  </div>

  <div class="group">
    <%= f.label :email, t("activerecord.attributes.user.email", :default => "Email"), :class => :label %>
    <%= f.text_field :email, :class => 'text_field' %>
    <span class="description">Enter email</span>
  </div>

  <div class="group">
    <%= f.label :encrypted_password, t("activerecord.attributes.user.encrypted_password", :default => "Encrypted password"), :class => :label %>
    <%= f.text_field :encrypted_password, :class => 'text_field' %>
    <span class="description">Enter password</span>
  </div>

  <div class="group">
    <%= f.label :reset_password_token, t("activerecord.attributes.user.reset_password_token", :default => "Reset password token"), :class => :label %>
    <%= f.text_field :reset_password_token, :class => 'text_field' %>
    <span class="description">Enter password</span>
  </div>

  <div class="group">
    <%= f.label :address, t("activerecord.attributes.user.address", :default => "Address"), :class => :label %>
    <%= f.text_field :address, :class => 'text_field' %>
    <span class="description">Enter address</span>
  </div>

  <div class="group">
    <%= f.label :phone_numer, t("activerecord.attributes.user.phone_numer", :default => "Phone numer"), :class => :label %>
    <%= f.text_field :phone_numer, :class => 'text_field' %>
    <span class="description">Enter phone number</span>
  </div>

  <div class="group">
    <%= f.label :avatar_uid, t("activerecord.attributes.user.avatar_uid", :default => "Avatar uid"), :class => :label %>
    <%= f.text_field :avatar_uid, :class => 'text_field' %>
    <span class="description">Enter avatar</span>
  </div>
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), admin_users_path, :class => "text_button_padding link_button" %>
</div>

app/views/admin/users/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/admin/users/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_users_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_user_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_user_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> User</h2>
    <div class="inner">
      <%= form_for @user, :url => admin_user_path(@user), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/users/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_users_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_user_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Users</h2>
    <div class="inner">
      <table class="table">
        <tr>
          <th>
            <%= link_to 'Full name', admin_users_path(sort_by_full_name: true, per_page: "#{session['per_page'].nil? ? 20 : session['per_page']}" ) %>
          </th>
          <th>Email</th>
          <th>
            Number Register Courses
          </th>
          <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @users.each do |user| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= link_to user.full_name, admin_user_path(user) %>
          </td>
          <td>
            <%= link_to user.email, admin_user_path(user) %>
          </td>
          <td>
            <%= user.courses.count %>
          </td>
          <td>
            <%= user.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_user_path(user) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_user_path(user) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_user_path(user), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
          <%= paginate @users %>
        </div>

      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/users/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_users_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_user_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  User</h2>
    <div class="inner">
      <%= form_for :user, :url => admin_users_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/users/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_users_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_user_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_user_path %></li>
    </ul>
  </div>
  <div class="content">
    <div class="inner">
        <p>
          <b><%= t("activerecord.attributes.admin_user.full_name", :default => t("activerecord.labels.full_name", :default => "Full name")) %>:</b>
          <%= @user.full_name %>
        </p>
        <p>
          <b><%= t("activerecord.attributes.admin_user.email", :default => t("activerecord.labels.email", :default => "Email")) %>:</b>
          <%= @user.email %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.address", :default => t("activerecord.labels.address", :default => "Address")) %>:</b>
          <%= @user.address %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.phone_numer", :default => t("activerecord.labels.phone_numer", :default => "Phone numer")) %>:</b>
          <%= @user.phone_numer %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.role", :default => t("activerecord.labels.role", :default => "Role")) %>:</b>
          <%= @user.role %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.avatar_uid", :default => t("activerecord.labels.avatar_uid", :default => "Avatar uid")) %>:</b>
          <%= @user.avatar_uid %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_user_path(@user), :class => "button" %>
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_user_path(@user), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>