config/routes.rb
Educare::Application.routes.draw do

  root :to =>'posts#index'

  devise_for :users, :controllers => {:sessions => 'sessions', :registrations => 'registrations'}

  namespace :admin do
    resources :users
    resources :posts
    resources :categories
    resources :courses
    resources :teachers
  end

  resources :posts, :only => [:show, :index]
  resources :courses, :only => [:show, :index]
  resources :teachers, :only => [:show, :index]

  match '/gioi-thieu' => 'pages#about_us'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web App</title>
  <%= stylesheet_link_tag 'web_app_theme' %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><%= link_to "Educare Vn", admin_users_path %></a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <li><%= link_to t("web-app-theme.profile", :default => "Frontend"), root_path, target: "_blank" %></a></li>
          <li><%= link_to "Logout", destroy_user_session_path %> </li>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf">
          <li class="<%= controller.controller_path == 'admin/users' ? 'active' : '' %>">
            <a href="<%= admin_users_path %>">Users</a>
          </li>
          <li class="<%= controller.controller_path == 'admin/posts' ? 'active' : '' %>">
            <a href="<%= admin_posts_path %>">Posts</a>
          </li>
          <li class="<%= controller.controller_path == 'admin/categories' ? 'active' : '' %>">
            <a href="<%= admin_categories_path %>">Categories</a>
          </li>
         <li class="<%= controller.controller_path == 'admin/courses' ? 'active' : '' %>"><a href="<%= admin_courses_path %>">Courses</a></li> <li class="<%= controller.controller_path == 'admin/teachers' ? 'active' : '' %>"><a href="<%= admin_teachers_path %>">Teachers</a></li></ul>
      </div>
    </div>
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> Educare Vn.</p>
          </div>
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Educare</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="page1">
  <div class="body1">
    <%= render '/layouts/shared/header' %>
    <%= render '/layouts/shared/banner' %>

    <% flash.each do |key, msg| %>
      <%= content_tag :div, class: "alert alert-#{key} alert-cardzee", id: "notice" do %>
          <a class="close" data-dismiss="alert" href="#">&times;</a>
          <%= msg %>
      <% end %>
    <% end %>
    <div class="body2">
      <div class="main main_body">
        <section id="content">
          <%= render 'layouts/shared/scroller' %>
          <div class="box1">
            <%= yield %>
            <article class="right sidebar">
              <%= yield :sidebar %>
            </article>
          </div>
        </section>
        <%= render 'layouts/shared/footer' %>
      </div>
    </div>
  </div>
</body>
</html>